---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{ include "aiven-klog.fullname" . }}
  namespace: nais-system
  labels:
    {{- include "aiven-klog.labels" . | nindent 4 }}
spec:
  command:
    - kafkactl
    - consume
    - nais-system.aiven-klog
    - --verbose
  env:
    - name: KAFKA_CTL_CONFIG
      value: /tmp/empty.yaml
    - name: KAFKA_CTL_WRITABLE_CONFIG
      value: /tmp/writable.yaml
    - name: BROKERS
      value: $(KAFKA_BROKERS)
    - name: CONTEXTS_DEFAULT_TLS_ENABLED
      value: "true"
    - name: CONTEXTS_DEFAULT_TLS_CERT
      value: $(KAFKA_CERTIFICATE_PATH)
    - name: CONTEXTS_DEFAULT_TLS_CERTKEY
      value: $(KAFKA_PRIVATE_KEY_PATH)
    - name: CONTEXTS_DEFAULT_TLS_CA
      value: $(KAFKA_CA_PATH)
  image: deviceinsight/kafkactl:latest
  kafka:
    pool: {{ .Values.aiven.project | required ".Values.aiven.project is required." }}
