apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: {{ include "aiven-klog.fullname" . }}
  namespace: nais-system
  labels:
    {{- include "aiven-klog.labels" . | nindent 4 }}
spec:
  pool: {{ .Values.aiven.project | required ".Values.aiven.project is required." }}
  acl:
    - team: nais-system
      application: aiven-klog
      access: read
  config:
    retentionHours: 24
