---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: klog
  namespace: nais-system
spec:
  command:
    - kafkactl
    - consume
    - nais-system.klog
  env:
    - name: KAFKA_CTL_CONFIG
      value: /tmp/empty.yaml
    - name: BROKERS
      value: $(KAFKA_BROKERS)
    - name: CONTEXTS_DEFAULT_TLS_ENABLED
      value: "true"
    - name: CONTEXTS_DEFAULT_TLS_CERT
      value: $(KAFKA_CERTIFICATE_PATH)
    - name: CONTEXTS_DEFAULT_TLS_CERTKEY
      value: $(KAFKA_PRIVATE_KEY_PATH)
    - name: CONTEXTS_DEFAULT_TLS_CA
      value: $(KAFKA_CA_PATH)
  image: deviceinsight/kafkactl:latest
  kafka:
    pool: {{ .Values.aiven.project }}
