---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels: { { - include "klog.labels" . | nindent 4 } }
  name: { { include "klog.name" . } }
spec:
  groups:
    - name: "aiven-klog"
      rules:
        - alert: AbsentKlogOverTime
          expr: absent_over_time(loki:service:loglevel:count1m{service_namespace="nais-system", service_name="aiven-klog"}[1h])
          for: 5m
          annotations:
            description: "Aiven klog has not logged for an hour, there should be a constant stream of Kafka logs."
            action: "Check to see if it's running, or maybe it has lost access to Aiven?"
            dashboard_url: "https://monitoring.nais.io/goto/Df9PxqLNg?orgId=1"
          labels:
            severity: warning
            namespace: nais-system

        - alert: NoKlogsGroupedByWithOffset
          expr: count(loki:service:loglevel:count1m{service_namespace="nais-system", service_name="aiven-klog"} offset 1h) by (k8s_cluster_name) unless count(loki:service:loglevel:count1m{service_namespace="nais-system", service_name="aiven-klog"}) by (k8s_cluster_name)
          for: 5m
          annotations:
            description: |
              This is test expression, to try different ways to check for absents. If you see this and AbsentKlogOverTime notify Kyrre.
              Aiven klog has not logged for an hour, there should be a constant stream of Kafka logs.
            action: "Check to see if it's running, or maybe it has lost access to Aiven?"
            dashboard_url: "https://monitoring.nais.io/goto/Df9PxqLNg?orgId=1"
          labels:
            severity: warning
            namespace: nais-system

        - alert: NoKlogsGroupPresentfoverTime
          expr: group(present_over_time(loki:service:loglevel:count1m{service_namespace="nais-system", service_name="aiven-klog"}[5m])) by (k8s_cluster_name) unless group(loki:service:loglevel:count1m{service_namespace="nais-system", service_name="aiven-klog"}) by (k8s_cluster_name)
          for: 5m
          annotations:
            description: |
              This is test expression, to try different ways to check for absents. If you see this and AbsentKlogOverTime notify Kyrre.
              Aiven klog has not logged for an hour, there should be a constant stream of Kafka logs.
            action: "Check to see if it's running, or maybe it has lost access to Aiven?"
            dashboard_url: "https://monitoring.nais.io/goto/Df9PxqLNg?orgId=1"
          labels:
            severity: warning
            namespace: nais-system
