apiVersion: aiven.io/v1alpha1
kind: ServiceIntegration
metadata:
  name: klog
  namespace: nais-system
spec:
  authSecretRef:
    name: aiven-operator-api-token
    key: token

  project: {{ .Values.aiven.project }}
  integrationType: kafka_logs

  sourceServiceName: {{ .Values.aiven.serviceName }}
  destinationServiceName: {{  .Values.aiven.serviceName }}

  kafkaLogs:
    kafka_topic: nais-system.klog
