dependencies:
  - allOf:
      - aiven-operator
      - naiserator
      - kafkarator
environmentKinds:
  - tenant
values:
  aiven.project:
     description: Aiven project name
     displayName: Aiven Project Name
     config:
       type: string
     computed:
       template: '"{{ .Env.aiven_project }}"'
  aiven.serviceName:
     config:
       type: string
     description: On the nav tenant, this must be set to "aivenProjectName"-kafka
     displayName: Aiven Service Name
